name = "server"
main = "src/index.ts"
compatibility_date = "2024-11-08"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
MY_VAR = "my-variable"
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNmRiYTk2YzYtM2FhYy00MTA2LWFlNjQtNzU2MDk5N2YxNGY3IiwidGVuYW50X2lkIjoiZDIwMjUwMzRmZmE1ZDQ1MGQ2M2JkMWIxNmMwYTY1ODY2NTVhZGMzYjhiYjE5N2U1OTE4YzFlYjQ1ZWQ2NDY1YiIsImludGVybmFsX3NlY3JldCI6IjZlZTBhOGViLWExNGQtNDgzMy1iZWM4LWEyNDcwNDk0OTcyNyJ9.c7i21NMfTfm8seYnPPWAwjV9XlT2LQvpYN0MIU_RBHI"


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1